# Server
server:
  port: 5000

# Spring DATASOURCE (DataSourceAutoConfigration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polling_app?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

# Hibernate Logging
logging:
  level:
    org.hibernate.sql: DEBUG

