# Server
server:
  port: 5001

# Spring DATASOURCE (DataSourceAutoConfigration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polling_app?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true # (?? ????? ??? ??)
    # clean-disabled: true    # ????? ? ??? ?? ??(??? ??? ?? ?? ??)

# Hibernate Logging
logging:
  level:
    org.hibernate.sql: DEBUG

# App Properties
app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 604800000

